"""empty message

Revision ID: 0d00fa813645
Revises: c3b7f7b61a2f
Create Date: 2017-09-03 11:20:17.693125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d00fa813645'
down_revision = 'c3b7f7b61a2f'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('modified_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customer', 'vk_users', ['modified_by_user_id'], ['id'])
    op.create_foreign_key(None, 'customer', 'vk_users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_column('customer', 'modified_by_user_id')
    op.drop_column('customer', 'created_by_user_id')
    # ### end Alembic commands ###


def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

