"""empty message

Revision ID: 1318ab22c10e
Revises: 06e94e1f8fe6
Create Date: 2017-08-24 19:40:55.291352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1318ab22c10e'
down_revision = '06e94e1f8fe6'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('control_system_floor_sensor', sa.Boolean(), nullable=True))
    op.add_column('room', sa.Column('control_system_other', sa.String(length=200), nullable=True))
    op.add_column('room', sa.Column('control_system_room_sensor', sa.Boolean(), nullable=True))
    op.add_column('room', sa.Column('control_system_type', sa.String(length=200), nullable=True))
    op.add_column('room', sa.Column('earthed_cable_screen', sa.Boolean(), nullable=True))
    op.add_column('room', sa.Column('earthed_chicken_wire', sa.Boolean(), nullable=True))
    op.add_column('room', sa.Column('earthed_other', sa.String(length=200), nullable=True))
    op.add_column('room', sa.Column('max_temp_installation', sa.Boolean(), nullable=True))
    op.add_column('room', sa.Column('max_temp_other', sa.String(length=200), nullable=True))
    op.add_column('room', sa.Column('max_temp_planning', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'max_temp_planning')
    op.drop_column('room', 'max_temp_other')
    op.drop_column('room', 'max_temp_installation')
    op.drop_column('room', 'earthed_other')
    op.drop_column('room', 'earthed_chicken_wire')
    op.drop_column('room', 'earthed_cable_screen')
    op.drop_column('room', 'control_system_type')
    op.drop_column('room', 'control_system_room_sensor')
    op.drop_column('room', 'control_system_other')
    op.drop_column('room', 'control_system_floor_sensor')
    # ### end Alembic commands ###


def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

