"""empty message

Revision ID: 76dc18dacf3e
Revises: fe83658de445
Create Date: 2017-07-29 13:54:46.367398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76dc18dacf3e'
down_revision = 'fe83658de445'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'line1',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('address', 'postnumber',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('company', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('company', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('company', 'orgnumber',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('customer', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('customer', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'customer', ['id'])
    op.alter_column('filled_form_modified', 'form_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('filled_form_modified', 'request_form',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('filled_form_modified', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('filled_form_modified', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invite', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invite', 'inviter_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('room', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('invite', 'inviter_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('invite', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('filled_form_modified', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('filled_form_modified', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('filled_form_modified', 'request_form',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('filled_form_modified', 'form_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_constraint(None, 'customer', type_='unique')
    op.alter_column('customer', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('customer', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('company', 'orgnumber',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('company', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('company', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('address', 'postnumber',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('address', 'line1',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

