"""empty message

Revision ID: 79113c023158
Revises: dfb523c59dcf
Create Date: 2017-08-19 23:56:29.139971

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '79113c023158'
down_revision = 'dfb523c59dcf'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    op.rename_table('room_types_info', 'room_type_info')
    op.execute('ALTER SEQUENCE room_types_info_id_seq RENAME TO room_type_info_id_seq')
    op.execute('ALTER INDEX room_types_info_pkey RENAME TO room_type_info_pkey')

def downgrade_():
    op.rename_table('room_type_info', 'room_types_info')
    op.execute('ALTER SEQUENCE room_type_info_id_seq RENAME TO room_types_info_id_seq')
    op.execute('ALTER INDEX room_type_info_pkey RENAME TO room_types_info_pkey')



def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
