"""empty message

Revision ID: a0792ed2ba6a
Revises:
Create Date: 2017-07-18 19:23:04.306260

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'a0792ed2ba6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line1', sa.String(length=200), nullable=True),
    sa.Column('line2', sa.String(length=200), nullable=True),
    sa.Column('postnumber', sa.SmallInteger(), nullable=True),
    sa.Column('postal', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('phone', 'email', 'mobile', name='contacttype'), nullable=True),
    sa.Column('value', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('orgnumber', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('orgnumber')
    )
    op.create_table('company_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('filled_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('customer_name', sa.String(length=250), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('vk_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('given_name', sa.String(length=50), nullable=True),
    sa.Column('family_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('user', 'companyAdmin', 'admin', name='userrole'), nullable=True),
    sa.Column('signature', sa.Binary(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('filled_form_modified',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('filled_form_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('request_form', sa.JSON(), nullable=True),
    sa.Column('form_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['filled_form_id'], ['filled_form.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['vk_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('invite',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('company', 'create_company', name='invitetype'), nullable=True),
    sa.Column('inviter_user_id', sa.Integer(), nullable=True),
    sa.Column('invitee_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['invitee_user_id'], ['vk_users.id'], ),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['vk_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('oauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('token', sqlalchemy_utils.types.json.JSONType(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['vk_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['vk_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_contact')
    op.drop_table('oauth')
    op.drop_table('invite')
    op.drop_table('filled_form_modified')
    op.drop_table('vk_users')
    op.drop_table('filled_form')
    op.drop_table('company_contact')
    op.drop_table('company')
    op.drop_table('contact')
    op.drop_table('address')
    # ### end Alembic commands ###


def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('product_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('manufacturor_id', sa.Integer(), nullable=True),
    sa.Column('mainSpec', sa.SmallInteger(), nullable=True),
    sa.Column('secondarySpec', sa.SmallInteger(), nullable=True),
    sa.Column('catagory', sa.Enum('cable_inside', 'cable_outside', 'mat_inside', 'mat_outside', 'single_inside', 'single_outside', name='productcatagory'), nullable=True),
    sa.ForeignKeyConstraint(['manufacturor_id'], ['manufacturor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('effect', sa.Numeric(precision=8), nullable=True),
    sa.Column('product_type_id', sa.Integer(), nullable=True),
    sa.Column('specs', sa.JSON(), nullable=True),
    sa.Column('restrictions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('product_type')
    op.drop_table('manufacturor')
    # ### end Alembic commands ###
