"""empty message

Revision ID: c3b7f7b61a2f
Revises: 3baefe3849e0
Create Date: 2017-09-02 12:11:43.208012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c3b7f7b61a2f'
down_revision = '3baefe3849e0'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    op.rename_table('oauth', 'flask_dance_oauth')
    op.execute('ALTER SEQUENCE oauth_id_seq RENAME TO flask_dance_oauth_id_seq')
    op.execute('ALTER INDEX oauth_pkey RENAME TO flask_dance_oauth_pkey')

def downgrade_():
    op.rename_table('flask_dance_oauth', 'oauth')
    op.execute('ALTER SEQUENCE flask_dance_oauth_id_seq RENAME TO oauth_id_seq')
    op.execute('ALTER INDEX flask_dance_oauth_pkey RENAME TO oauth_pkey')


def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
