"""empty message

Revision ID: dfb523c59dcf
Revises: faa0950a27ec
Create Date: 2017-08-19 16:17:05.471976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb523c59dcf'
down_revision = 'faa0950a27ec'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_types_info', sa.Column('outside', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'room_types_info', ['id'])
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room_types_info', type_='unique')
    op.drop_column('room_types_info', 'outside')
    # ### end Alembic commands ###


def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

