"""empty message

Revision ID: ea1383395d7a
Revises: bf32d4d3d466
Create Date: 2017-07-29 17:27:01.746970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea1383395d7a'
down_revision = 'bf32d4d3d466'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - pleadse adjust! ###
    op.alter_column(table_name='address', column_name='line1', new_column_name='address1')
    op.alter_column(table_name='address', column_name='line2', new_column_name='address2')
    op.alter_column(table_name='address', column_name='postnumber', new_column_name='post_code')
    op.alter_column(table_name='address', column_name='postal', new_column_name='post_area')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name='address', column_name='address1', new_column_name='line1')
    op.alter_column(table_name='address', column_name='address2', new_column_name='line2')
    op.alter_column(table_name='address', column_name='post_code', new_column_name='postnumber')
    op.alter_column(table_name='address', column_name='post_area', new_column_name='postal')
    # ### end Alembic commands ###


def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
