"""empty message

Revision ID: 06e94e1f8fe6
Revises: 1bd1d5a238e9
Create Date: 2017-08-20 00:56:41.843391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06e94e1f8fe6'
down_revision = '1bd1d5a238e9'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('area', sa.Numeric(precision=8, scale=3), nullable=True))
    op.add_column('room', sa.Column('heated_area', sa.Numeric(precision=8, scale=3), nullable=True))
    op.add_column('room', sa.Column('maxEffect', sa.Numeric(precision=8, scale=3), nullable=True))
    op.add_column('room', sa.Column('normalEffect', sa.Numeric(precision=8, scale=3), nullable=True))
    op.add_column('room', sa.Column('outside', sa.Boolean(), nullable=True))
    op.drop_column('room', 'specs')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('specs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('room', 'outside')
    op.drop_column('room', 'normalEffect')
    op.drop_column('room', 'maxEffect')
    op.drop_column('room', 'heated_area')
    op.drop_column('room', 'area')
    # ### end Alembic commands ###


def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

