"""empty message

Revision ID: 1bd1d5a238e9
Revises: 79113c023158
Create Date: 2017-08-20 00:00:34.471735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd1d5a238e9'
down_revision = '79113c023158'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('room_type_info_id', sa.Integer(), nullable=True))
    op.create_foreign_key('room_room_type_info_id_fkey', 'room', 'room_type_info', ['room_type_info_id'], ['id'])
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('room_room_type_info_id_fkey', 'room', type_='foreignkey')
    op.drop_column('room', 'room_type_info_id')
    # ### end Alembic commands ###


def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
