"""empty message

Revision ID: 1dd200ca49a1
Revises: 53ac850c9fbf
Create Date: 2017-10-16 14:10:29.381366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd200ca49a1'
down_revision = '53ac850c9fbf'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_type', sa.Column('per_meter', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_type', 'per_meter')
    # ### end Alembic commands ###

