"""empty message

Revision ID: 22813fdedef8
Revises: 6edb9ea1b0fc
Create Date: 2017-09-25 15:01:35.203520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22813fdedef8'
down_revision = '6edb9ea1b0fc'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_contact')
    op.add_column('company', sa.Column('contact_email', sa.String(length=100), nullable=False, server_default='none'))
    op.alter_column('company', 'contact_email', server_default=None)
    op.add_column('company', sa.Column('contact_name', sa.String(length=200), nullable=False, server_default='none'))
    op.alter_column('company', 'contact_name', server_default=None)
    op.add_column('company', sa.Column('contact_phone', sa.String(length=20), nullable=False, server_default='none'))
    op.alter_column('company', 'contact_phone', server_default=None)
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'contact_phone')
    op.drop_column('company', 'contact_name')
    op.drop_column('company', 'contact_email')
    op.create_table('company_contact',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='company_contact_company_id_fkey'),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], name='company_contact_contact_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='company_contact_pkey'),
    sa.UniqueConstraint('id', name='company_contact_id_key')
    )
    # ### end Alembic commands ###


def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
