"""empty message

Revision ID: 4fb71d79ceed
Revises: 968e85af2a71
Create Date: 2017-08-10 19:41:16.983598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4fb71d79ceed'
down_revision = '968e85af2a71'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_item_modifications')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_item_modifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('archived', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('room_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('pdf_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['room_item_id'], ['room.id'], name='room_item_modifications_room_item_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['vk_users.id'], name='room_item_modifications_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='room_item_modifications_pkey')
    )
    # ### end Alembic commands ###


def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

