"""empty message

Revision ID: 51553242fff0
Revises: 8567118ae370
Create Date: 2017-08-10 17:48:20.571892

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51553242fff0'
down_revision = '8567118ae370'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='filled_form_modified',
        column_name='request_form',
        new_column_name='json')
    op.alter_column(
        table_name='filled_form_modified',
        column_name='form_data',
        new_column_name='pdf_json')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='filled_form_modified',
        column_name='json',
        new_column_name='request_form')
    op.alter_column(
        table_name='filled_form_modified',
        column_name='pdf_json',
        new_column_name='form_data')
    # ### end Alembic commands ###


def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
