"""empty message

Revision ID: 53ac850c9fbf
Revises: 2f2e3f032bb6
Create Date: 2017-10-16 13:41:56.768832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ac850c9fbf'
down_revision = '2f2e3f032bb6'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_type', sa.Column('self_limiting', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_type', 'self_limiting')
    # ### end Alembic commands ###

