"""empty message

Revision ID: 6edb9ea1b0fc
Revises: f9b0e6243f92
Create Date: 2017-09-22 18:13:26.382644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6edb9ea1b0fc'
down_revision = 'f9b0e6243f92'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('curcuit_breaker_size', sa.SmallInteger(), nullable=True))
    op.add_column('room', sa.Column('ground_fault_protection', sa.Numeric(precision=8, scale=3), nullable=True))
    op.add_column('room', sa.Column('installation_depth', sa.Numeric(precision=8, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'installation_depth')
    op.drop_column('room', 'ground_fault_protection')
    op.drop_column('room', 'curcuit_breaker_size')
    # ### end Alembic commands ###


def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

