"""empty message

Revision ID: 8567118ae370
Revises: ea1383395d7a
Create Date: 2017-07-30 16:38:28.642140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8567118ae370'
down_revision = 'ea1383395d7a'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'post_area',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.add_column('room', sa.Column('specs', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'specs')
    op.alter_column('address', 'post_area',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

