"""empty message

Revision ID: 9067a3084fe1
Revises: 0f7006aa4743
Create Date: 2017-10-11 08:27:54.924101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9067a3084fe1'
down_revision = '0f7006aa4743'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'name')
    op.add_column('customer_data', sa.Column('customer_name', sa.String(length=200), nullable=True))
    op.drop_column('customer_data', 'name')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_data', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('customer_data', 'customer_name')
    op.add_column('customer', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

