"""empty message

Revision ID: 968e85af2a71
Revises: d1bee5e3c161
Create Date: 2017-08-10 19:02:48.648917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '968e85af2a71'
down_revision = 'd1bee5e3c161'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_item_modifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('room_item_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('json', sa.JSON(), nullable=False),
    sa.Column('pdf_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['room_item_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['vk_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_constraint('filled_form_modified_user_id_fkey', 'room_item', type_='foreignkey')
    op.drop_column('room_item', 'user_id')
    op.drop_column('room_item', 'json')
    op.drop_column('room_item', 'archived')
    op.drop_column('room_item', 'date')
    op.drop_column('room_item', 'pdf_json')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_item', sa.Column('pdf_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('room_item', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('room_item', sa.Column('archived', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('room_item', sa.Column('json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('room_item', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('filled_form_modified_user_id_fkey', 'room_item', 'vk_users', ['user_id'], ['id'])
    op.drop_table('room_item_modifications')
    # ### end Alembic commands ###


def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

