"""empty message

Revision ID: a5bf6f438b26
Revises: f84e63e57e3c
Create Date: 2017-10-13 11:42:01.435437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5bf6f438b26'
down_revision = 'f84e63e57e3c'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'construction_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('customer', 'construction_change')
    op.drop_column('customer', 'construction_nek400')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('construction_nek400', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('customer', sa.Column('construction_change', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('customer', 'construction_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

