"""empty message

Revision ID: b1e466e73ab7
Revises: 55a2a59ee496
Create Date: 2017-08-15 19:36:06.994352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1e466e73ab7'
down_revision = '55a2a59ee496'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_item_modifications', sa.Column('pdf_specs', sa.JSON(), nullable=True))
    op.add_column('room_item_modifications', sa.Column('specs', sa.JSON(), nullable=True))
    op.drop_column('room_item_modifications', 'pdf_json')
    op.drop_column('room_item_modifications', 'json')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_item_modifications', sa.Column('json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('room_item_modifications', sa.Column('pdf_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('room_item_modifications', 'specs')
    op.drop_column('room_item_modifications', 'pdf_specs')
    # ### end Alembic commands ###


def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

