"""empty message

Revision ID: c16ed716af74
Revises: 3be8c0a07968
Create Date: 2017-10-10 15:05:20.609255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16ed716af74'
down_revision = '3be8c0a07968'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_data', sa.Column('name', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'customer_data', ['id'])
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer_data', type_='unique')
    op.drop_column('customer_data', 'name')
    # ### end Alembic commands ###


def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

