"""empty message

Revision ID: ceffe0cedd90
Revises: 1318ab22c10e
Create Date: 2017-08-24 21:57:21.641425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceffe0cedd90'
down_revision = '1318ab22c10e'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='room',
        column_name='control_system_type',
        new_column_name='control_system_designation')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='room',
        column_name='control_system_designation',
        new_column_name='control_system_type')
    # ### end Alembic commands ###


def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
