"""empty message

Revision ID: db2af8b2f3fe
Revises: 613fca311ba9
Create Date: 2017-09-30 18:07:00.326024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db2af8b2f3fe'
down_revision = '613fca311ba9'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'inside_specs', ['id'])
    op.create_unique_constraint(None, 'outside_specs', ['id'])
    op.add_column('room', sa.Column('control_system_limit_sensor', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'control_system_limit_sensor')
    op.drop_constraint(None, 'outside_specs', type_='unique')
    op.drop_constraint(None, 'inside_specs', type_='unique')
    # ### end Alembic commands ###


def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

