"""empty message

Revision ID: f84e63e57e3c
Revises: 9067a3084fe1
Create Date: 2017-10-11 10:28:45.022196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f84e63e57e3c'
down_revision = '9067a3084fe1'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'construction_id', 'owner_id')
    op.alter_column('customer', 'owner_id', 'construction_id')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'construction_id', 'owner_id')
    op.alter_column('customer', 'owner_id', 'construction_id')
    # ### end Alembic commands ###


def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
