"""empty message

Revision ID: fe83658de445
Revises: ff77f008aee2
Create Date: 2017-07-29 13:22:10.884090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe83658de445'
down_revision = 'ff77f008aee2'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    op.rename_table('filled_form', 'room')
    op.execute('ALTER SEQUENCE filled_form_id_seq RENAME TO room_id_seq')
    op.execute('ALTER INDEX filled_form_pkey RENAME TO room_pkey')

def downgrade_():
    op.rename_table('room', 'filled_form')
    op.execute('ALTER SEQUENCE room_id_seq RENAME TO filled_form_id_seq')
    op.execute('ALTER INDEX room_pkey RENAME TO filled_form_pkey')

def upgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_products():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
